// https://www.englishclub.com/vocabulary/phrasal-verbs-list.htm
/* 
var words = [
{ word: 'chest', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['pit'] },
{ word: 'waist', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['cintura'] },
{ word: 'limbs', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['extremitats', 'braços i cames'] },
{ word: 'lung', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['pulmó'] },
{ word: 'heel', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['taló'] },
{ word: 'belly', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['ventre', 'panxa'] },
{ word: 'hip', 				tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['cadera'] },
{ word: 'forehead', 		tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['front', '(front de la cara)'] },
{ word: 'brow', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['front', '(front de la cara)'] },
{ word: 'eyebrow', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['cella'] },
{ word: 'cheek', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['galta', 'mejilla'] },
];/*
{ word: 'cheekbone', 		tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['pòmul', '(de la galta)'] },
{ word: 'breast', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['pit'] },
{ word: 'elbow', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['colze'] },
{ word: 'navel', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['melic'] },
{ word: 'scruff', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['pescuezo', 'nuca'] },
{ word: 'chin', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['barbeta'] },
{ word: 'knee', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['genoll'] },
{ word: 'fist', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['puny'] },
{ word: 'knuckle', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['artell', 'nudillo'] },
{ word: 'wrist', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['canell', 'muñeca'] },
{ word: 'gut', 				tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['intestí', 'budell', 'budells'] },
{ word: 'thigh', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['cuixa'] },
{ word: 'thumb', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['dit polze', 'polze', 'pulgar'] },
{ word: 'gullet', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['gola', 'esófag', 'gaznate', 'garganta'] },
{ word: 'eyelids', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['parpelles'] },
{ word: 'rib', 				tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['costella'] },
{ word: 'Never', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['mai'] },
{ word: 'Hardly ever', 		tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['casi mai'] },
{ word: 'Rarely', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['rarament'] },
{ word: 'Seldom', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['alguna vegada', 'algunes vegades'] },
{ word: 'Occasionally', 	tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['ocasionalment'] },
{ word: 'Sometimes', 		tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['algunes vegades'] },
{ word: 'Often', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['de tant en tant'] },
{ word: 'Frecuently', 		tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['amb freqüència', 'freqüentment', 'freqüent', 'frecuentment'] },
{ word: 'Normally', 		tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['normalment'] },
{ word: 'Usually', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['usualment'] },
{ word: 'Always', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['sempre'] },
{ word: 'wits', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['perspicacia', 'inteligència', 'sentit del humor'] },
{ word: 'cough', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['estornudar', 'tossir'] },
{ word: 'spit', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['escupir'] },
{ word: 'within', 			tipus: 'P', 	res_ok: 0, res_ko: 0, meaning: ['dintre de'] },
{ word: 'whilst', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['mentres que', 'mentre que'] },
{ word: 'tangle', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['enredo'] },
{ word: 'don', 				tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['vestir'] },
{ word: 'pebbles', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['còdol', 'guijarro)'] },
{ word: 'glance', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['mirada', 'cop d\'ull'] },
{ word: 'cloack', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['capa'] },
{ word: 'snatch', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['agafar bruscament'] },
{ word: 'seize', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['agafar fort'] },
{ word: 'wretch', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['desgraciat'] },
{ word: 'drown', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['ofegar'] },
{ word: 'utter', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['pronunciar', 'proferir'] },
{ word: 'utterly', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['absolutament'] },
{ word: 'fine', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['multa'] },
{ word: 'bear', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['pertànyer', 'pertanyer'] },
{ word: 'tidings', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['notícies'] },
{ word: 'appointment', 		tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['cita', 'designació'] },
{ word: 'sturdy', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['robust'] },
{ word: 'reliable', 		tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['segur', 'confiable'] },
{ word: 'bucked', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['galleda', 'cubell', 'cubo'] },
{ word: 'hire', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['llogar', 'contractar'] },
{ word: 'fee', 				tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['quota', 'preu periòdic'] },
{ word: 'pry', 				tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['palanca'] },
{ word: 'shiver', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['escalofrio', 'calfred'] },
{ word: 'shiver', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['tiritar'] },
{ word: 'reach', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['alcanzar', 'arribar'] },
{ word: 'stagger', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['tambalejar'] },
{ word: 'creep', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['arrastrar-se', 'arrastrar'] },
{ word: 'snore', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['roncar'] },
{ word: 'owe', 				tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['deure', 'deber'] },
{ word: 'duty', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['deure', 'obligació', 'deber'] },
{ word: 'thick', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['gruixut', 'groixut', 'espès'] },
{ word: 'weary', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['cansat'] },
{ word: 'glad', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['content', 'alegre'] },
{ word: 'rough', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['aspre'] },
{ word: 'pluck', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['arrancar', 'arrencar', 'agafar'] },
{ word: 'soak', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['remullar', 'empapar'] },
{ word: 'rave', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['delirar'] },
{ word: 'cleaver', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['ganivet de carniser'] },
{ word: 'befall', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['succeïr', 'succeir', 'esdevenir'] },
{ word: 'sew', 				tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['cosir'] },
{ word: 'seldom', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['rarament'] },
{ word: 'rush', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['presa'] },
{ word: 'yawn', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['badallar', 'bostezar'] },
{ word: 'loom', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['teler', 'màquina de telar'] },
{ word: 'spiky', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['puntiagut', 'punxagut'] },
{ word: 'bitter', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['amarg'] },
{ word: 'grief', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['dolor', 'mal', 'aflicció', 'pesar'] },
{ word: 'deserve', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['merèixer'] },
{ word: 'scorn', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['desdeny', 'menyspreu', 'desdén'] },
{ word: 'forth', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['endavant'] },
{ word: 'faint', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['dèbil', 'tènue', 'desmaiat'] },
{ word: 'faint', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['desmaiar'] },
{ word: 'toil', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['treball físic', 'esforç'] },
{ word: 'raw', 				tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['cru', 'crudo'] },
{ word: 'narrow', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['estret'] },
{ word: 'craven', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['covard'] },
{ word: 'wiggle', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['bellugar', 'remenar', 'menear'] },
{ word: 'rope', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['corda'] },
{ word: 'regret', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['lamentar', 'saber greu'] },
{ word: 'knot', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['nús', 'nus'] },
{ word: 'tie', 				tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['lligar amb un nús', 'lligar amb un nus', 'lligar'] },
{ word: 'tie', 				tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['corbata'] },
{ word: 'fasten', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['cordar', 'fixar', 'abrochar'] },
{ word: 'brake', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['fre'] },
{ word: 'swallow', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['empasar', 'empassar', 'engullir', 'tragar'] },
{ word: 'shallow', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['superficial', 'poc profund'] },
{ word: 'advise', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['aconsellar'] },
{ word: 'avoid', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['evitar'] },
{ word: 'sway', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['influència'] },
{ word: 'slap', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['bofetada'] },
{ word: 'clap', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['aplaudir'] },
{ word: 'grope', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['tentar', '(de tentació)'] },
{ word: 'smooth', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['llis', '(de superfície llisa)'] },
{ word: 'hesitate', 		tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['vacilar'] },
{ word: 'ripe', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['madur'] },
{ word: 'stride', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['pas llarg', 'gambada', 'zancada'] },
{ word: 'tear', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['llàgrima', 'estrip'] },
{ word: 'supple', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['flexible'] },
{ word: 'hasty', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['apresurat', 'precipitat'] },
{ word: 'beneath', 			tipus: 'P', 	res_ok: 0, res_ko: 0, meaning: ['a sota'] },
{ word: 'moot', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['discutible'] },
{ word: 'bald', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['calvo'] },
{ word: 'dusk', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['vespre'] },
{ word: 'fair', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['just', 'raonable'] },
{ word: 'fairly', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['bastant'] },
{ word: 'pretty', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['bastant'] },
{ word: 'pretty', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['bonic'] },
{ word: 'quite', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['bastant'] },
{ word: 'lush', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['exuberant', 'exhuberant', 'exoberant'] },
{ word: 'tight', 			tipus: 'Adj', 	res_ok: 0, res_ko: 0, meaning: ['ajustat', 'apretat'] },
{ word: 'butt', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['culata', 'extrem', 'cul'] },
{ word: 'tar', 				tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['alquitrà'] },
{ word: 'stink', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['pudor'] },
{ word: 'stink', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['fer pudor'] },
{ word: 'alley', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['carreró'] },
{ word: 'cling', 			tipus: 'V', 	res_ok: 0, res_ko: 0, meaning: ['adherir', 'aferrar'] },
{ word: 'pillow', 			tipus: 'N', 	res_ok: 0, res_ko: 0, meaning: ['coixí'] },
{ word: 'duly', 			tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['degudament'] },
{ word: 'properly', 		tipus: 'Adv', 	res_ok: 0, res_ko: 0, meaning: ['adecuadament'] }
];
*/
